name: Continuous Deployment

on:
  push:
    branches:
      - develop
      - main

jobs:
  set_environment:
    name: Set environment
    runs-on: ubuntu-latest
    outputs:
      current_environment: ${{ steps.setenv.outputs.current_environment }}
    steps:
      - id: setenv
        run: |
          [ ${{ github.ref }} == refs/heads/develop ] && ENVIRONMENT=develop
          [ ${{ github.ref }} == refs/heads/main ] && ENVIRONMENT=production
          echo "current_environment=${ENVIRONMENT}" >> $GITHUB_OUTPUT

  show_env:
    name: Show env
    runs-on: ubuntu-latest
    needs: set_environment
    environment: ${{ needs.set_environment.outputs.current_environment }}
    steps:
      - name: Print env
        env:
          HOST: ${{ secrets.HOST }}
          ENVIRONMENT: ${{ needs.set_environment.outputs.current_environment }}
          NORMAL: test
          REPO: ${{ secrets.REPO }}
          GH_REPO: ${{ github.repository }}
        run: |
          echo ${ENVIRONMENT} | sed 's/./& /g'
          echo ${HOST} | sed 's/./& /g'
          echo ${NORMAL} | sed 's/./& /g'
          echo ${REPO} | sed 's/./& /g'
          echo ${GH_REPO} | sed 's/./& /g'
